name: first_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0  # أضف هذا السطر هنا
  provider: ^6.1.1
  # تأكد أنك تحتاج فعلاً لهذه المكتبة بالأسفل لأن اسمها يشبه اسم مشروع افتراضي
  flutter_application_1: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/nn.png